on:
  push:
    branches:
      - main

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!Cristiano Schmitt"
        python -m pip install --upgrade pip
        pip install build